### ISSUE TITLE
Job: Mid-Senior Scala Engineer | London | Onsite | Full Time | £50K-85K 

### ISSUE THREAD

**Issue by levinotik** [Functional-Programming-Slack/community#1]
@Functional-Niko

A bit more info:
Depop is a growing social marketplace that lets you buy and sell unique fashion items and is now scaling the engineering team after a £50 million Series-C investment. With a strong focus on and love for functional programming, you have the opportunity to work in an agile and diverse environment to help a vibrant community grow.

The tech stack for this role include: Scala - Play framework - AWS - Postgres - Kinesis

As such you should have experience in Scala and some of its libraries.
If you are interested and want to apply, please follow the link here (http://bit.ly/DepopScalaLondon), or you can email me at nikolaus@functionalworks.com or PM me here.

**Comment by FunctionalNiko** [comment]
@levinotik thanks mate :)
