### ISSUE TITLE
Job: Software Engineer (Haskell) | NYC | TQ Tezos - smart contract-based products

### ISSUE THREAD

**Issue by nikkisinny** [Functional-Programming-Slack/community#13]
TQ is a New York-based blockchain technology company advancing the Tezos project. In collaboration with the Tezos Foundation in Switzerland and Nomadic Labs in Paris, TQ builds products on Tezos and developer tools to help others do so.

TQ Tezos is hiring Senior Backend Engineers and Senior Front End Engineers to work out of their office in New York. 

Technically, you'll have experience with at least one of the following:

**Frontend**—React, ReasonML, TypeScript

**Backend**— Haskell, OCaml/ReasonML,
Bonus points: Formal verification tools: Coq, Agda, Idris 

Does this sound like a fit for you? You can apply [here](https://www.works-hub.com/jobs/senior-software-engineer-in-new-york-united-states-of-america-c7e0b#utm_source=github&utm_medium=job&utm_campaign=n.sadozai) or email nicole@functionalworks.com

**Comment by levinotik** [comment]
This role still open @nicolesadozai? If not, let's close it please.
