### ISSUE TITLE
Job: Functional Software Engineer (Clojure) | NYC | Onsite | Full-time| Up to 150k

### ISSUE THREAD

**Issue by SherylFunctionalWorks** [Functional-Programming-Slack/community#14]
**Droit** is a Fintech company based out of New York City, using **Clojure** and Clojurescript to automate complex legal and real-time decision systems. They're creating software called Adept, in order to allow any cross-asset trade to be legal. Fundamentally, they're changing the market and driving innovation around automating complex global legal frameworks and real-time decision systems.

Email me (sheryl@functionalworks.com) and I'd love to hop on a call with anyone who is interested.
Job Description: https://bit.ly/3fc5hRD

Role Title: **Software Engineer** 
Location: NYC (temporarily remote)

**General Requirements**
High degree of curiosity with the ability to ask thoughtful questions and solve challenging problems.
Able to use functional programming to design simple and elegant solutions.
Able to envision a variety of solutions and to clearly articulate them and explain the trade-offs.
Enjoys working with others and sharing knowledge to get the best results.
Possesses excellent interpersonal skills.
Willing to work hard and leave ego at the door.

**Technical Requirements**
Solid experience with a programming language e.g. Java, Python, Clojure
Enthusiastic about functional programming*

**Highly Desirable**
Experience programming Clojure or ClojureScript or another Lisp
Experience using a RDBMS such as Postgres
Experience building React applications and RESTful APIs
Experience in formal verification – for example Coq

**Comment by levinotik** [comment]
and this

**Comment by SherylFunctionalWorks** [comment]
Just re-opened this week for hiring! :)
