### ISSUE TITLE
Job: Mid-Senior Scala Engineer | London | Onsite | Full Time

### ISSUE THREAD

**Issue by filosganga** [Functional-Programming-Slack/community#15]
I have an opportunity if a Scala software engineer position, with high focus on functional programming. 

You will work with me and Fabio Labella (@systemfw) (one of the core maintainer of cats-effect and fs2) to help evolving the architecture of Kaluza. Kaluza is a platform that aim to power the green energy retail market worldwide. 

The only requirement is that you know already the Scala syntax and you are interested in functional programming and distributed systems. We can then train you, It is a very good learning experience.

The position is based in London and allow working remotely few days per week.

If interested please get in touch either with me of Fabio via DM.

**Comment by levinotik** [comment]
This role still open @filosganga? If not, let's close it please.
