### ISSUE TITLE
[HIRING] [ONSITE] [NYC] [SCALA + cats, shapeless, monix, fs2 ] [Associate OR Associate Director Level]

### ISSUE THREAD

**Issue by SherylFunctionalWorks** [Functional-Programming-Slack/community#16]
Hi everyone! Scotiabank is looking to expand their team in NYC. They’re looking for a Software Engineer to join the FICC QTAS (Quant Tech Architecture & Solutions) team. This is a small 4 person team of functional programming enthusiasts!

In this role, you will help develop strategies and technical solutions using Scala for Scotiabank’s rates and commodities trading desks. Directly supporting the trading desks, some things you will help to build include execution strategies, pricing models, automation workflows, plus ongoing systems development as the team expands its reach through the bank.

Job description: http://bit.ly/2TNAJMO

Send me an email sheryl@functionalworks.com to hear more about this role.

**Comment by levinotik** [comment]
ditto
