### ISSUE TITLE
[HIRING] [ONSITE] [SAN FRANCISCO] [ UP TO 150K] [OPEN TO REMOTE IF IN US] [OCAML]

### ISSUE THREAD

**Issue by SherylFunctionalWorks** [Functional-Programming-Slack/community#17]
I hope everything is doing okay throughout this tough time :) If you or anyone you know is looking for a new role, please feel free to reach out to me.

O(1) Labs is a series-A start-up located in San Francisco. They are trying to innovate the latest technology to improve security and improve blockchain technologies. CODA Protocol is the blockchain created by O(1) Labs which is the first constant-sized blockchain that condenses into the size of a tweet. This makes it easier and cheaper to build products using CODA Protocol.

They are looking for Protocol Engineers to join their team where you will be working on core networking, cryptography, and reliability aspects of the protocol.

Send me a message if you're interested, or email me sheryl@functionalworks.com :)

Job Description: http://bit.ly/2QdUZ7T

**Comment by levinotik** [comment]
ditto
