### ISSUE TITLE
[JOB] [REMOTE FOR US CANDIDATES] [CLOJURESCRIPT]

### ISSUE THREAD

**Issue by Pmgubbey1** [Functional-Programming-Slack/community#18]
ArcheMedX are a well-funded, revenue-producing, early-stage company that applies behavioral science to improve learning and generate actionable insights to improve clinical care. The ArcheMedX platform accelerates the research of new medicines and delivery of better care to millions of patients.

They are looking for Senior ClojureScript Developers who can work remotely if based out of Charlottesville (Only for US Candidates!)

https://bit.ly/2TllsSF

**Comment by levinotik** [comment]
This role still open @Pmgubbey1? If not, let's close it please.
