### ISSUE TITLE
[HIRING] [NYC-BASED, TEMPORARILY REMOTE] [SCALA] [COMPETITIVE SALARY]

### ISSUE THREAD

**Issue by SherylFunctionalWorks** [Functional-Programming-Slack/community#19]
**Digital Asset**, a leading provider of distributed ledger technology, are looking for Software Engineers to join their DAML Application Runtime team in NYC, London, or Zurich.

**You will be responsible for:**
✔️ Developing the ecosystem of tools, APIs, and frameworks used directly by customers in their ledger client applications
✔️ Delivering high quality and well-tested code efficiently and at pace in a Scala-focused codebase (with a little bit of Haskell)

Let's chat📲 Send me an email **(sheryl@functionalworks.com)** or DM me on here and I'd love to tell you more about the role, the company, and how DLT provides value.

Job Description: https://hubs.li/H0wxvky0

**Comment by levinotik** [comment]
this too :)

**Comment by SherylFunctionalWorks** [comment]
Still open!
