### ISSUE TITLE
[HIRING][Austin][Denver][DC][Remote][Typescript][Scala]

### ISSUE THREAD

**Issue by psilospore** [Functional-Programming-Slack/community#20]
MotoRefi is hiring: https://functional.works-hub.com/companies/motorefi

We're interested in hiring someone with an interest in FP. We use typescript, fp-ts, io-ts, and a bit of Scala. Familiarity with a functional programming language is a plus.

We have a preference to have people in the Denver, Austin, or Washington DC office after the office opens up but we're also open to permanent remote after this period.

At the moment we can only hire US citizens.

**Comment by levinotik** [comment]
This role still open @psilospore? If not, let's close it please.

**Comment by psilospore** [comment]
Hey @levinotik,

It is but seems that we've changed the posting. I've updated the link. Thanks for letting me know!
