### ISSUE TITLE
Senior Full-Stack Software Engineer [HIRING][Tel Aviv-Yafo][Israel][TypeScript][fp-ts]

### ISSUE THREAD

**Issue by SRachamim** [Functional-Programming-Slack/community#21]
## About FundGuard

FundGuard is revolutionising the investment funds technology space, offering game changing operational and technology efficiencies and paving way for financial and operational innovation.

FundGuard is a cloud-based investment funds operating system powered by artificial intelligence. It helps asset and fund managers administer investments across mutual funds, ETFs, hedge funds, insurance, and pension. FundGuard leverages modern cloud technologies and a revolutionary multi-dimension real-time design to transform an underserved industry that is limited today by archaic, primarily on-premise, batch based and non-scalable technology.

The company is backed by US venture firms, and led by an experienced team with successful exits, who are investment funds industry experts, as well as machine learning and enterprise cloud systems technology leaders.

## Responsibilities

- Design a data-driven UI, rich in graphs and tables using latest ReactJS.
- Fetch data from many micro-services and expose it as a coherent API gateway with NodeJs and GraphQL.
- Write performant, testable and simple purely-functional code with fp-ts.
- Work with typing (TypeScript).
- Write unit tests, integration tests, functional tests, property-based tests and snapshot tests (TDD).
- Benchmark and optimise performance issues on UI and API.
- Compose responsive layouts and accessible interactive interfaces with HTML and CSS. 
- Work in a scrum team with Git, pull-requests and code-reviews.

## Requirements

- Expert level experience in web technologies (TypeScript, Functional Programming)
- Experience in building enterprise grade applications, that are highly responsive supporting high volume of concurrent users
- Understanding of Functional Programming paradigm and other programming concepts like immutability, pure functions and function compositions.
- Experience with SPA applications, performance optimisation, functional testing, integration testing, property-based testing and unit tests.

**Comment by levinotik** [comment]
This role still open @SRachamim? If not, let's close it please.

**Comment by SRachamim** [comment]
Still open.

**Comment by gustavorodarte** [comment]
HI, @SRachamim how can apply I?

**Comment by levinotik** [comment]
Closing unless this is still open @SRachamim
