### ISSUE TITLE
Senior Scala/Spark Data Engineer position | global | full time | full remote

### ISSUE THREAD

**Issue by DCameronMauch** [Functional-Programming-Slack/community#22]
My company is looking for a data engineer with strong Scala and Spark experience.
The job is full remote, and we have employees all over the country, and even a few in other countries.
Very competitive salary, great benefits, and takes diversity/inclusion quite seriously.
Other technologies include Python, AWS (EMR, ECS, S3), Airflow, Jenkins, Github.
Our Scala is fairly functional in style, but not into deep Cats or Scalaz, but we may end up using ZIO.
The person would need to be available for meetings in the morning or very early afternoon NYC time.
Maybe like twice a year travel to NYC for company get togethers.
Please PM me with your resume if you are interested.

**Comment by levinotik** [comment]
This role still open @DCameronMauch? If not, let's close it please.
