### ISSUE TITLE
How to join this slack community?

### ISSUE THREAD

**Issue by justin-hackin** [Functional-Programming-Slack/community#34]
I couldn't find any instructions for joining this slack group. Can I get an invite?

**Comment by ghost** [comment]
In the same bind. Would love an invite. My email is `carre.matthieu.lucien@gmail.com`.
Thanks!

**Comment by tldrlol** [comment]
Slackin has ceased to work, I believe this should work now: https://fpchat-invite.herokuapp.com.

**Comment by justin-hackin** [comment]
Yay I'm in, thanks @tldrlol
