### ISSUE TITLE
Job : Developer position | Haskell | OCaml | F# | Luxoft, India | Full Time

### ISSUE THREAD

**Issue by Nekomyst** [Functional-Programming-Slack/community#4]
Job opportunity at **Luxoft, Bangalore, India** for the position of **Developer** (Haskell,OCaml or F#). Kindly reach out : https://www.linkedin.com/in/shweta-gupta-6b8224195/  :slightly_smiling_face:

**Comment by levinotik** [comment]
This role still open @CaptainNick? If not, let's close it please.

**Comment by Nekomyst** [comment]
Yeah, this can be closed. 👍
