### ISSUE TITLE
Job: Senior Software Engineer (Scala) | NYC, Portland, Chicago | Onsite | Competitive

### ISSUE THREAD

**Issue by SherylFunctionalWorks** [Functional-Programming-Slack/community#6]
Gemini, a leading cryptocurrency exchange in NYC who's looking to hire Senior Software Engineers in their NY, Portland, and Chicago offices. In this role, you'll be using Scala on the backend to develop new products and features across all aspects of the business. (FP oriented)

Email me (sheryl@functionalworks.com) and I'd love to hop on a call with anyone who is interested.

Job Description: http://bit.ly/2TLTz7c
 
**Role overview**
We are looking for a highly motivated and experienced Senior Engineer to help design, build and architect systems as part of Gemini’s broader product lines and services. The team is focused on innovating how we deliver software and will be working with every engineering team to improve our ability to deliver high quality solutions to our customers fast and efficiently. Even more so than in other engineering roles, this individual must be an outstanding communicator and bridge-builder across different parts of the engineering organization. You’ll put your experience to work with helping development teams design and implement their solution. This role can be based in our New York, Chicago, or Portland, Oregon offices.

**Help us Build the Future of Money**
Gemini Trust Company, LLC (Gemini) is a licensed digital asset exchange and custodian. We built the Gemini platform so customers can buy, sell, and store digital assets (e.g., Bitcoin, Ethereum, and Zcash) in a regulated, secure, and compliant manner.

**Responsibilities:**
- Working with product, design and other engineering teams to deliver simple solutions for application developers.
- Cultivating a high-performance culture within your team that iterates frequently and learns continuously without sacrificing product quality.
- Setting performance goals for team members; evaluating performance; providing coaching and facilitating professional development.
- Recruiting and hiring world-class engineers to work on Gemini’s products.

**Comment by levinotik** [comment]
This role still open @SherylFunctionalWorks? If not, let's close it please.
