### ISSUE TITLE
Cannot access website to sign up

### ISSUE THREAD

**Issue by brendonakay** [Functional-Programming-Slack/community#63]
Hello, I cannot access http://fpchat.com/ or https://invite-fpchat.com/. Is this community still active and accepting new members?

**Comment by levinotik** [comment]
Hey there, sorry for the confusion. Please visit https://fpslack.com to request an invite

**Comment by brendonakay** [comment]
Thank you so much!

**Comment by srid** [comment]
Hey @brendonakay - out of curiosity, where did you come across those two links (currently broken)?

**Comment by brendonakay** [comment]
@srid It had been on a few sites I saw from a Google search. Here's an example of one https://techbeacon.com/app-dev-testing/46-slack-groups-developers. They're outdated, so not surprised the URL was wrong.
