### ISSUE TITLE
RFC: migrate from Slack to Discord

### ISSUE THREAD

**Issue by levinotik** [Functional-Programming-Slack/community#65]
## Description

The purpose of this RFC is to evaluate and discuss the possibility, benefits and disadvantages of moving the FP Slack community from Slack to Discord. 

## Context

Unlike Discord, Slack is not intended for open communities. It generally assumes that all members of the organization have a pre-existing, collegial relationship. As such, it lacks many of the tools and features that make sense for an open community. 

Additionally, Slack's free plan allows us to access only the last 90 days of message history. Messages and files older than 90 days are inaccessible to us. To access them, we'd need to upgrade to the paid tier.

We currently have ~170 members that we'd be billed for under Slack's "Fair Billing Policy". We could theoretically lower the total cost by pruning certain accounts and/or getting Slack to recognize our status as a non-profit (likely a tedious task).

As of the time of writing, the monthly bill on the paid plan would be:

**$8.75 USD x (number of active members as calculated by Slack) x 1 month = $1,435 USD**

## Benefits of migrating to Discord

![Xnip2022-11-07_18-38-20](https://user-images.githubusercontent.com/514174/200438475-59faa326-d40e-4f82-b8a7-b7e0340f4c93.jpg)

Some of the concrete Discord benefits are:

* Free, with *complete* message history preservation.

* Some FP Slack members report that this would be an "app consolidation" (e.g. they are already mainly using Discord).

* Flexible moderation features.

* Better threading support.

![Xnip2022-11-07_18-19-02](https://user-images.githubusercontent.com/514174/200438494-c7414531-f4c0-4045-b0a0-ab6059710da9.jpg)

* Useful features for IRL meetups and events

![Xnip2022-11-07_18-21-14](https://user-images.githubusercontent.com/514174/200438520-9a0e4c00-4daa-44ca-9a96-f6491cf6cc41.jpg)

<img width="639" alt="143080123-a4ec2d06-2cac-49df-a0a2-0407cb66bd9f" src="https://user-images.githubusercontent.com/514174/200438548-0d08e74f-be4f-43a4-a68c-864a5c856ad7.png">

## Disadvantages of migrating to Discord

* Not all members will make the switch, either due to missing the updates/announcements or not wanting to move to a new platform.

* We'd need to configure the Discord server from scratch.

* We may need to migrate some apps/integrations.

## Data and feedback we need to gather

* Who would find migrating to Discord to be beneficial? Who would find it to be a pain point?

* Is the limited message history in Slack a problem? Would having a complete message history be helpful in the FP Slack community?

* Any data on whether incoming members prefer Slack or Discord?

* Would it be possible to collect money from _willing_ members to pay for Slack? I think we've always assumed this is a nonstarter

**Comment by levinotik** [comment]
I personally have become more and more fond of Discord after using it with several open communities. In the past, I probably leaned towards a possible migration not being worth it, but now see the many benefits.

**Comment by svarlet** [comment]
> Some FP Slack members report that this would be an "app consolidation" (e.g. they are already mainly using Discord).

Well, I'm not using Discord, only using Slack. Where does that leave us? Toss a coin? 😆 

There's a lot of "you had to be there" in live messaging, consequently I've never been disappointed by the history quotas. 

I appreciate it may be because I've joined many open source communities in slack (elm, elixir, flutter, etc) to seek help "in the moment", and occasionally help the wanderers.

If anything need to be preserved I can take notes offline, and if the world must know about X, I can always blog or post something on stackoverflow about X, but I certainly don't expect the world to search a Slack/Discord to find this piece of information. 

All this to say I personally don't hoard past conversations, and I'm happy with Slack (even more so since all my other messaging communities/workplaces use Slack).

**Comment by togakangaroo** [comment]
I get the reasoning but moving to discord is likewise, a hard sell for me. I'm already in 15 slacks and IRC via emacs. Adding another app to the mix just makes it really hard. If we could set up decent bridges to irc that would be worth considering, but as it stands I would probably drop out.

**Comment by ghost** [comment]
I think one big problem with this idea is that there already is a 12,500-member Functional Programming Discord: https://discord.gg/rDdspBBGcA

It's as complete as you'd want an FP Discord to be, with some demographic and cultural differences from FP Slack. As with most Discord communities, members are primarily pseudonymous. Probably younger and less professionally experienced than FP Slack, in the aggregate. They also focus on pure and statically typed languages (with a tinge more overt elitism about it). Anyway.

FP Slack being on Slack makes it capture the attention of a different demographic. Moving it to Discord might make it more difficult to do so. It runs a high risk of becoming redundant. FP Slack is an amazing resource to network and find job opportunities, and has attracted recruiters who notably did not find their way to the FP Discord (they also have job postings, just not the exact same ones).

**Comment by mkspcd** [comment]
Regarding Slack / Discord : I use Slack for work, so I open it every day.

The few communities I follow on Discord => I go there once a month (at best) since they switch to Discord. 

Discord may have all the features in the world, if I never log into the app and never use them, they serve no purpose.

**Comment by etorreborre** [comment]
Just one data point: I am already using Slack for work and other communities. Having to use Discord would mean having one more app open which is not very appealing to me.

**Comment by kristiannotari** [comment]
I'm a heavy discord user and while I see the reasons why to move there I'm also aware that there are going to be people which legitimately ask to stay on slack. I think there's no clear winner as of now, both platforms come with pros and cons for different types of people and usages.

I personally prefer Discord. Faster, simpler, better notifications sync across devices (IMHO) and threading (there are forums now too) and much more 2022. We can also have voice calls and stuff like that freely. There are a lot of moderation tools and integrations/bots too.

I mean, if you had to start over for some important reasons, I doubt slack would be your first guess as of now. Discord would be the way to go. You can create a great discord server even by migrating the actual slack now but some people are not doing that for sure.

**Comment by stevebluck** [comment]
I use both but I actually prefer Slack, not sure if it's because I see it more as a professional setting in comparison to Discord. I use Discord mainly for other things such as gaming but I wouldn't personally be toooo fussed if it was moved.

**Comment by levinotik** [comment]
@svarlet 

> Well, I'm not using Discord, only using Slack. Where does that leave us? Toss a coin? 

Haha no. The fact that for some people moving to Discord would mean more apps, not less, should've been listed on the disadvantages side to counteract the consolidation advantage listed on the Discord advantages side.

**Comment by levinotik** [comment]
Excellent feedback so far, thank you everyone. The goal was to finally have an explicit and formal conversation about this and give everyone a chance to weigh in, so this is great.

**Comment by srid** [comment]
It looks like the consensus is getting to be to stay on Slack ... however, if there is interest in further exploring options, there is also Zulip: https://funprog.zulipchat.com/ managed by myself and @TheMatten

The Agda community already uses it as well: https://agda.zulipchat.com/

Unlike Discord/Slack, Zulip is open-source. They also provide a free hosting option for open-source projects and non-profit communities.

**Comment by kristiannotari** [comment]
I'm curious, not aggressive, but I'd like to know why slack or zulip could be better alternatives. Cause I'm missing the reasons why a new (new, not talking about this migration specifically) community should go for Slack or Zulip instead of Discord.

Discord has everything you're likely to want in a community even with the free option. It has voice calls, meetings and event organizations. It has bots almost for everything. It's quick and much more 2022 if that's an advantage :D. Yes, it's not the professional tool for organization, maybe due to its nature, but it clearly moved in this direction in the recent years (at least for communities and not companies).

What are the reasons to keep using chat-only based services with limitations (slack) or others like zulip (which I tried the mobile app and it's lacking a lot from my point of view)? Am I missing a great advantage of slack/zulip-like apps for communities?

edit: I mean, besides "open source", which is not a great deal for me for this specific scenario (community management)
edit2: the only thing I consider a pro in slack is the ability to differentiate login credentials per space/community instead of discord unique account and then username change between them

**Comment by levinotik** [comment]
> I'm curious, not aggressive, but I'd like to know why slack or zulip could be better alternatives. Cause I'm missing the reasons why a new (new, not talking about this migration specifically) community should go for Slack or Zulip instead of Discord.

@kristiannotari I personally tend to agree with you. I think there are even folks here who agree that Discord would be a better option if we were starting anew, but feel differently about the practicalities of migrating. I assume there are some who feel Slack is inherently the better option, but most of what I've seen is people who do see the merits of Discord, but have other concerns related to whether we can successfully migrate, whether it means having yet another app open for them, etc. 

Lots of views either way which is why I wanted to discuss and see if there's anything resembling a consensus.

**Comment by kristiannotari** [comment]
"resembling" is the key here!

I guess there's not going to be a consensus on migrating. What I personally think about migrating is: being stuck on an "old" media is not helpful for the community itself (growing, getting new members, and such) if the "new" media is technically superior (events, voice calls, forums, moderation, roles, and so on).

The cons of migrating (and not properly of the medias theirselves) is that some people could be left behind due to a) not wanting to migrate/have another app/hate discord or b) losing the "transition" moment.

Either ways my take is: if they didn't want to, they eventually solve their problems with apps due to discord taking over the world in a few years from now anyway (😄) or if they lost the moment they just come back to the community even if that's on discord. Having discord also opens up the way to a bigger audience as of now (IMO) but that's up to you to discover if it's a good or a bad thing (😄)

**Comment by svarlet** [comment]
I see the same list of "superior" features branded multiple times without a list of the problems they would actually solve for us, so I'm not sold on the value of forcefully moving almost 16,000 users to another platform yet.

**Comment by kristiannotari** [comment]
> I see the same list of "superior" features branded multiple times without a list of the problems they would actually solve for us, so I'm not sold on the value of forcefully moving almost 16,000 users to another platform yet.

- free history ( -> everything can be searched freely)
- events organization in platform ( -> easier grouping and contact for members even for IRL events)
- voice calls whenever you want with multiple people ( -> ability to switch to pair programming, teaching, helping, discussing by voice freely)
- forums for easy writing/finding of thread-like discussions ( -> which means better questions, hopefully, better search ability for new users and alike and a much better thread-like system instead of the one in slack)
- better moderation (I guess, but I could be mistaken here) cause discord is actually made for managing communities
- a quicker/more fluent app (in my experience at least) especially on mobile

It's not like they solve "problems", there are no "real problems" with slack, it's just a more pleasant experience for a community IMHO. If that's worth migrating? That's hard to answer. I tend to yes (better now than later), but opinions may vary.

**Comment by kristiannotari** [comment]
About the "forcefully moving" it's not like we have customers with paid subscription which are actually forcefully moved to another subscription/app/service. It's more a "hey, we're keeping our community up to date with the latest in terms of community management, giving you more options and services, want to join us? Here's the link"

**Comment by levinotik** [comment]
@svarlet @kristiannotari 

> so I'm not sold on the value of forcefully moving almost 16,000 users to another platform yet

I just wanted to note that we're obviously not forcefully doing anything, in the sense that if we migrated to Discord, people are free to move over to Discord or not. Secondly, and perhaps more importantly, there are not 16K active members. There are many, many members who never participate in or even look at FP Slack (for those people who might not even see any announcements about the migration, we'd leave a trail behind so that they'll see info about the move if/when they do ever visit our Slack org). 

So in my opinion, the people we should really be focused on are the ones who are most active and who participate the most. Obviously, we want everyone to have a voice, but I think it's fair to give less weight to people who never even visit our Slack, as opposed to very active users who may have a view one way or the other about this. 

Finally, I just wanted to clarify that I do _not_ have strong views about this one way or the other. I tend to agree with @kristiannotari about the benefits of Discord and if we were to start today, it would be the obvious choice IMO. But, I'm ok with whatever the community decides, as with most other decisions.

**Comment by cdimitroulas** [comment]
I'm fine either way, though I tend to agree that Discord is "better" overall in terms of features and usability. The downside is that I need to use Slack anyways for work so it's not like I would be able to stop using Slack and save some resources 😅

**Comment by joelmccracken** [comment]
IMO given there is already a huge fp community on discord, this change makes no sense. I'd possibly suggest matrix/element instead.

**Comment by jderochervlk** [comment]
I use both, so the switch wouldn't be hard for me. The benefits of the longer history would make it easier to search for things. I'm already in some other FP servers on Discord, so that would help me consolidate my focus over there. Slack at this point is just work and this server.

**Comment by cdimitroulas** [comment]
> IMO given there is already a huge fp community on discord, this change makes no sense. I'd possibly suggest matrix/element instead.

I went to take a look at this FP discord and my first impressions were pretty bad, I have to say. The first thing I saw was an April fool's joke about how they are adding a "JS" channel to talk about FP in JS. There is no such channel of course...
The FP Slack community seems very welcoming and we have folks doing FP in all kinds of languages from JS and PHP through to the more stereotypical ones like Haskell and Scala.
This other pre-existing FP community on discord seems much more focused on the latter types of languages with no accommodation for any others, which is a shame.

My point is, I disagree with the opinion that another FP community on discord "makes no sense".

**Comment by SeeThruHead** [comment]
that would be a shame, as i wouldn't follow.

**Comment by enricopolanski** [comment]
I have seen this happen multiple times with other open source or tech communities. The experience has **always** been better and it cannot be understated how important and relevant it is to keep older messages, not just in public channels but in personal private communication as well. Less popular channels for more niche languages are absolutely killed by Slack's history policies making them ghost towns.

There is one and only one reason to not do this switch: if the community doesn't have a decent influx of new members. Each community, unavoidably, will have members leaving, and the healtiness of it depends on the ratio of leaving vs joining members.

When transitioning to Discord we will lose some members (mostly lurkers and rare posters), those members may make a difference in communities that are not growing. 

Thus, yes, switching to Discord is something we should absolutely look to do, we should've done that a long time ago. But please keep in mind that we, as a community, will need to make sure that our Discord and community is easy to find and join and do a bit of advertising to make sure we keep having new members joining us.

**Comment by levinotik** [comment]
I'm personally very partial to the views you outlined @enricopolanski

**Comment by levinotik** [comment]
> > IMO given there is already a huge fp community on discord, this change makes no sense. I'd possibly suggest matrix/element instead.
> 
> I went to take a look at this FP discord and my first impressions were pretty bad, I have to say. The first thing I saw was an April fool's joke about how they are adding a "JS" channel to talk about FP in JS. There is no such channel of course... The FP Slack community seems very welcoming and we have folks doing FP in all kinds of languages from JS and PHP through to the more stereotypical ones like Haskell and Scala. This other pre-existing FP community on discord seems much more focused on the latter types of languages with no accommodation for any others, which is a shame.
> 
> My point is, I disagree with the opinion that another FP community on discord "makes no sense".

@cdimitroulas I agree with you. And even if that other community were not operating in the way you described, I don't actually view our Slack org as being in competition with any other community and, to me, viewing ourselves as up against all the  FP discords is as arbitrary as viewing us as in competition with all chat groups generally. Sure, both would be FP communities on Discord, but so what? To me this move is about whether moving our particular org/community to Discord serves the interests and of our existing community and whether it aids/improves the conversations we're already having. The issue of the prospective newcomer having to choose between the two, the question of discoverability, etc are all second-order (at best) questions in my mind.

**Comment by levinotik** [comment]
I'm curious to hear from you all: who among you definitely would not be continuing to participate as a consequence of moving to Discord?

**Comment by srid** [comment]
@levinotik How about posting a `/poll` in `#general` channel of Slack?

<img width="389" alt="image" src="https://user-images.githubusercontent.com/3998/202044545-8182d780-1907-4dc9-b918-af16d246ae97.png">

**Comment by levinotik** [comment]
@srid I've thought about it and may do so. My concern, and you can all tell me if you think it's unfounded, is having people who don't really have any feeling about voting "just because" and diluting how meaningful the results are. I feel like participating in an extended discussion here provides us with a basic requirement that a) the people participating have read the proposal and that b) they care enough to sound off. I guess what I'm saying is that I worry that just clicking on a poll is so low-effort that it will cloud the results. Thoughts?

**Comment by levinotik** [comment]
Also @srid, would you stick around if we moved to Discord? Assuming Zulip and the other options you mentioned aren't being considered, do have any preference between Slack and Discord?

**Comment by srid** [comment]
That's a valid concern. Also, I'll point out the general principle that what people say they will do is not necessarily the same as what they actually do. :-P

> would you stick around if we moved to Discord? Assuming Zulip and the other options you mentioned aren't being considered, do have any preference between Slack and Discord?

I would stick around, yes, regardless of my preferences (which is to go with Zulip or Matrix). I actually like the message persistence of all these other chat forums, which is the big problem with Slack.

**Comment by joelmccracken** [comment]
@levinotik I for one would def stick around in the community, I'm in discord pretty often anyway

**Comment by joelmccracken** [comment]
Also, I'd like to propose that if we do decide to move, we do it as an experiment, making them parallel communities, with the possibility of eventually closing the slack version.

I think there are a fair number of semi-active who aren't always on and don't always follow all discussions, they just jump on whenever they have a question, or perhaps feel like chatting. If we do "shut down" the slack, odds are these people will be lost in the shuffle. I do get that not doing a clean switch from one app to another creates a risk of community bifurcation, but I don't know that the alternative is much better.

**Comment by enricopolanski** [comment]
Good point @joelmccracken.

I have recently seen few communities do the slack to discord jump, one of them being the Microsoft Playwright community and they've done so in parallel.

A more famous example might've been the huge migration from freenode to libera on IRC. They work in parallel, many migrated and abandoned freenode for good, some stay on freenode, but both communities function well.
