### ISSUE TITLE
Who to contact for a deactivated workspace?

### ISSUE THREAD

**Issue by andreacfromtheapp** [Functional-Programming-Slack/community#66]
Hi :)

apologies if this isn't the right place but I cannot find any contact to reactivate my FP Slack workspace access. I tried with the invite but it is not working. Only workspace admins can help.

I would like to re-join the community with my slack associated email/account. (which I'd send privately)

Please and thank you

**Comment by cdimitroulas** [comment]
Which invite did you try? Have you tried https://fpslack.com/?

**Comment by andreacfromtheapp** [comment]
Hi, yes I tried fpslack as advertised in the README https://github.com/Functional-Programming-Slack/community/blob/master/README.md#request-an-invite
