### ISSUE TITLE
Job: Software Engineer | Clojure | NYC or Remote | Up to $130k |

### ISSUE THREAD

**Issue by SherylFunctionalWorks** [Functional-Programming-Slack/community#8]
I'm working with PhoneWagon to help find a Remote Software Engineer using Clojure (must be located in the US). PhoneWagon is a beautiful and easy to use call tracking software that helps businesses grow their marketing spend by placing unique local phone numbers on each of their different marketing campaigns. In this role, you'll help design and operate environments that enable fast-paced development and deployments while achieving high availability, resiliency, and security.

If this is of interest, send me a DM or email me (sheryl@functionalworks.com)

**Job description: http://bit.ly/2NXDhED**

**Job Requirements:**
2+ years work experience as a software engineer 
Experience building highly-available and resilient backend services 
Knowledge of relational databases 
Authorized to work in the US

**What you will work on and develop your skills:**
Work on the JVM and in Clojure 
Experience with telephony (Asterisk, Kamailio, SIP, RTP) 
Experience with AWS (RDS, SQS, S3, Elasticache, ECS, Cloudformation, CodePipeline, etc) 
Work with containers (Docker) 
Continuous Delivery / Deployment

**Comment by levinotik** [comment]
Same for this
