### ISSUE TITLE
Job: Protocol Engineer (Jr./Sr.) SF | Haskell/OCaml | Any Functional Programming Background

### ISSUE THREAD

**Issue by QuanTruc112** [Functional-Programming-Slack/community#9]
The experience level is flexible, as long as you've worked with a functional language for 1+. Recently raised $15M this year.

No remote. US Only.

Full job spec here: https://functional.works-hub.com/jobs/software-engineer-san-francisco-ca-united-states-fbb0c

Please feel free to email me at quan@Functionalworks.com

**Comment by levinotik** [comment]
This role still open @QuanTruc112? If not, let's close it please.

**Comment by nicksebastian** [comment]
> This role still open @QuanTruc112? If not, let's close it please.

Please close this for me @levinotik, thank you!
